### ISSUE TITLE
Package deployer issue

### ISSUE THREAD

**Issue by totrickl** [WaelHamze/dyn365-ce-vsts-tasks#118]
I don't know where to look at. Found this place to leave question. 

In my project we currently use VSTS release process and MSCRM Package Deployer task for each solution being deployed to target environment. 
Can anyone explain why is Holding solution being created when solution version is higher then in target system. For example if on target version we have 19.0.5.1 and release deploys 19.0.5.2  solutionName_Upgrade version is created on target.

This behaviour causes release pipeline fail because, as I understand, it tries to delete Holding solution but fails with timeout. 

The main question I really need to know is "why Holding solution is being created at the first place?". And how can I control this? I have a deployment project in Visual studio solution and ImportConfig in there. No googling helped with this so far.

**Comment by drivardxrm** [comment]
Same problem here. I have opened a case at Microsoft, but I have no answer/workaround so far. I ended up doing a powershell script to be sure that I use the latest version of Microsoft.Xrm.Tooling.PackageDeployment.Powershell but I have the same timeout error when deleting the holding solution.

**Comment by totrickl** [comment]
> Same problem here. I have opened a case at Microsoft, but I have no answer/workaround so far. I ended up doing a powershell script to be sure that I use the latest version of Microsoft.Xrm.Tooling.PackageDeployment.Powershell but I have the same timeout error when deleting the holding solution.

Could you send a link to the ticket? I could find a use of that.

**Comment by drivardxrm** [comment]
Hi the case number is 119082124002258.
Please share if you find a solution.

**Comment by totrickl** [comment]
> 119082124002258

Where can I find it? No googling helping in this )

**Comment by LycraLout** [comment]
+1 on this.

It's an issue for us as well. The PackageDeployer is a great way to get C# to run on your deployments. We have managed to work around it until now by using the Install Solution and Apply Solution tasks before running the PackageDeployer. In that scenario, the PackageDeployer skips the installation of the solution because the versions match but will continue on and run our post import code. However, we now have the need to run some logic _before_ the solution imports. More hoops to jump through.

To answer your original question, the Holding solution is necessary in an upgrade to provide reference to items that need to be deleted. Applying the upgrade takes out any components that are not in the newer version (managed layers permitting that is). eg, Entity has fields A, B & C. In a newer release you find B redundant and delete it in source. New version of solution has fields A & C. Applying the upgrade and deleting the holding solution strips B out of the target.

FWIW, we have no problems with PackageDeployment tasks in our OnPremise installations. They run just fine.

**Comment by WaelHamze** [comment]
@totrickl this task just wraps the Package Deployer PowerShell Modules so I don't have much control over what package deployer does. I have updated the task to the latest modules you will need to update your package and use 9.1 in the SDK drop down. Although this is unlikely to fix your problem.

I have others have decided to turn off applying the upgrade if you have nothing to delete.

Check the below issues: https://github.com/WaelHamze/xrm-ci-framework/issues/224

I normally import solutions using the import solution task and use the package deployer for any other steps.
