### ISSUE TITLE
MSCRM Tool Installer: Allow input of version of the dependent CrmSdk packages

### ISSUE THREAD

**Issue by mathiasbl** [WaelHamze/dyn365-ce-vsts-tasks#131]
This idea comes from the [Power Apps Tool installer](https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerApps-BuildTools) which allows you to define the versions to use for each different packages as show in the image.

![image](https://user-images.githubusercontent.com/16224711/70849230-cd284300-1e7b-11ea-8ece-d72e23b0fc02.png)

Do you think this would be possible in your tasks? New versions are backwards compatible so should have no effect on your tasks. This would allow us to move forward to a newer version of a certain dependent crmsdk package without having to wait for a new release of your tasks.

**Comment by WaelHamze** [comment]
@mathiasbl yes that was my initial idea when I started this a couple of years ago. To load these dynamically from Nuget/PS Gallery. But many of the enterprise users have agents behind proxies and firewalls where access to Nuget and PS Gallery is blocked.

I was thinking to allow users to specify the path to the tools and they would be responsible for providing it.

Let me know what you think...

**Comment by mathiasbl** [comment]
The idea that enterprises block access to Nuget and PS Gallery worries me. The last years every website or program has references to NuGet/NPM packages. This means a agent can't do a NuGet restore on a project. I find this idea absurd but this is another discussion.

Any sort of control over the used crmsdk tooling would be nice. Either it being dynamically loaded or we having to provided the path to the crmsdk tooling.

**Comment by WaelHamze** [comment]
Many companies using repository management tools and proxy these so they can still access the libraries: https://guides.sonatype.com/repo3/quick-start-guides/proxying-maven-and-npm/

But that would involve custom nuget files and credentials which increases the complexity.

Can order the libraries in terms of priority that you think you should have access to provide your own version?

**Comment by mathiasbl** [comment]
I'm sorry I don't understand your question.

**Comment by WaelHamze** [comment]
@mathiasbl no worries, I mean there are many nuget and powershell libraries. Which ones you think are more important than others? (i.e. that ones that you find yourself needing to wait for next release)

**Comment by mathiasbl** [comment]
Personally I'm really waiting for the new features in the Microsoft.Xrm.Tooling.ConfigurationMigration packages to start using it in my pipeline. 

In general .. in order of importance for the tasks:
1. Microsoft.CrmSdk.CoreTools
3. Microsoft.CrmSdk.XrmTooling.PackageDeployment.PowerShell
3. Microsoft.Xrm.Tooling.ConfigurationMigration
4. Microsoft.Xrm.OnlineManagementAPI
5. Microsoft.PowerApps.Checker.PowerShell
6. Microsoft.Xrm.Tooling.CrmConnector.PowerShell

**Comment by WaelHamze** [comment]
@mathiasbl now that some of the important updates are out we can come back to this. I've been thinking about this and I think I can get this to work.

A number of questions/scenarios/thoughts below:

1. Let's assume we allow the user to input the version. So user enters v1 of solution packager. Now v2 of solution packager comes along with new parameters. Task gets updated to allow new parameters (same version). With this setup when extension gets updated, the task will fail as it will load v1. Only way around this is up the version of task. So user will have to specifically select the higher version of the task to take advantage.
2. Let's assume we allow the user to input the version. So user enters v1 of solution packager. Now v2 of solution packager comes. If user doesn't specifically change to v2 they will stay at that version even when extension gets updated. This can be an advantage and disadvantage at same time. Sometimes people create pipelines and leave them so having extension auto update is sometimes useful.
3. Do you think we should allow the user option to specify "latest" instead of specific version so pipeline picks up latest immediately?
4. Do you think the version should be set on the tools task or should we provide this in individual tasks?
5. Would you be able to try a preview version once this functionality is ready to provide any feedback before it gets pushed to public?

**Comment by mathiasbl** [comment]
1. Could you check which versions is being used and show an error if your tasks expects a higher version? Or check which version is used and either call the v1 or v2 version of the task. This would require maintaining multiple versions of the same task which is probably not what we want?
2. See 1?
3. Yes, the more options the better? Although choosing this options will probably break your pipeline sooner or later.
4. Tool installer task.
5. Yeah, i'll do my best to do so.

**Comment by WaelHamze** [comment]
@mathiasbl looking at this now. I think we can't get away from doing this in the current toolsets but one day would be great to have this working without consumer having to worry about versions of tools :)

FYI - the new online management API has some breaking changes in API interface, so latest is not always backwards compatible :)

**Comment by WaelHamze** [comment]
@mathiasbl could you please share an Azure DevOps account where I can share the preview? This should be different than one you normally have your extension installed to avoid any disruption to existing pipelines. You can send me private msg on linkedin or twitter if you can't share details here.

If anyone else would like to try this and provide feedback then let me know.
