### ISSUE TITLE
MSCRM Export Solution will not store extracted files into DevOps repository

### ISSUE THREAD

**Issue by huseyinazizcan** [WaelHamze/dyn365-ce-vsts-tasks#142]
Hi,

Using the "MSCRM Export Solution" task, I am able to successfully export a solution from my source instance into a folder of my choosing (within my repository). The job runs successfully and the log even says "UnManaged Solution Exported d:\a\1\s\ZipFile\Test_9_1_1_0.zip". The problem is that the file doesn't show up in my DevOps repository. I'm assuming that its stored on the agent machine and is not committed to DevOps. The same issue goes for the "MSCRM Extract Solution" task.

Is there anything I can do to make sure that it is committed and stored in my DevOps repository?

Thanks

**Comment by mattp65** [comment]
Part of the problem is that there is not a requirment to use a psecific solution for your repository. So you need to add steps to tie into your repository in your pipeline yourself. If you are using Git, then it's a matter of setting up the right Git commands to check in the changes. If your repository is using VSTS, then you can look at the TFVC Build Tasks extension to help with check-in.

**Comment by huseyinazizcan** [comment]
Thanks
