### ISSUE TITLE
Preview and license of VSTS tasks

### ISSUE THREAD

**Issue by MS4GitHub** [WaelHamze/dyn365-ce-vsts-tasks#2]
Hi Wael,

thanks for your great work!

I have a few questions:

- Since when have  "dyn365-ce-vsts-tasks" been available?

- What does preview means in general related to use it with TFS 2015 Update 3 and D365 for Sales (OnPremise)

- Do you recommend to use "xrm-ci-framework" for our environment instead of "dyn365-ce-vsts-tasks"?

- When will it be "released" for production?

- Will it be free of charge under the MIT license?

Kind regards,

Martin

**Comment by WaelHamze** [comment]
Hi Martin,

Thanks you. Answers below.

Since when have "dyn365-ce-vsts-tasks" been available? WH: This is a new repo, however the extension has been in market place since Jan 2017.

What does preview means in general related to use it with TFS 2015 Update 3 and D365 for Sales (OnPremise) WH: Preview means some tasks are still in preview. You should be able to use it with TFS 2015 and D365 on-premises

Do you recommend to use "xrm-ci-framework" for our environment instead of "dyn365-ce-vsts-tasks"? I would go for the tasks first as it will cover most of the use cases and then use xrm-ci-frameowork or other alternatives for the edge cases or custom requirements.

When will it be "released" for production? WH: The extension is in the marketplace so you can download it and install it.

Will it be free of charge under the MIT license? WH: The current version of the extension that is in the market place is free or charge. P.S. I have changed the license, MIT was the default license when the repo was created

I hope this helps.
