### ISSUE TITLE
Publishing in 8.2 On Prem Environment issues

### ISSUE THREAD

**Issue by subratgaur** [WaelHamze/dyn365-ce-vsts-tasks#53]
Hi, 

We are using this to publish in to a 8.2 Environment and are having issues where some of the components are not getting  updated. These components are getting updated when the solution import is done manually. 

Just to add to that, imports in to a creal OOB organization work fine, this problem is noticed only where there are existing solutions and new versions of the solution are being pushed.

I am wondering if this is related to the fact that the SDK used in the tool is >9.0. 

Is there a version of the tool with 8.2 SDK ? 

Thanks

**Comment by WaelHamze** [comment]
@subratgaur import solution API hasn't changed much since 8.2. At believe the same msg will be generated on the wire at the end. Anyway most of the solution import processing happens on the backend. The SDK call just upload the zip to the backend with a few parameters.

Are you using managed or unmanaged solutions?

I have seen scenario even on 9 where import via SDK and UI can lead to different behaviours. Normally I raise a case with MS and they get this fixed.

**Comment by subratgaur** [comment]
We  have tried publishing multiple times but we dont get a consistent result.  We are using managed solutions and as i mentioned earlier, this works fine if we do this on a out of the Box Organization. 

Problems only appear when we import the updated solution where an earlier version is already installed. 

Thanks

**Comment by WaelHamze** [comment]
You don't normally have to publish with managed solutions. I would suggest raising a case with MS.

Only time I saw this happening is if is there an unmanaged layer of the same component with that environment.

**Comment by WaelHamze** [comment]
Closing as there is no action I can take on this
