### ISSUE TITLE
MSCRM Tool Installer

### ISSUE THREAD

**Issue by crmdruid** [WaelHamze/dyn365-ce-vsts-tasks#63]
Good day Wael,

I hope you are doing well that side.
I am experiencing an unusual issue this week.
I have tried on another Azure Dev Ops Instance which isn't in part of the organisations to be sure.

In the private one, I setup an release pipeline with the MSCRM Tool Installer extension.

In the organisation one, the release pipeline has an vstest tasks for smoke tests which is why the errors are slightly different.

Private Azure Dev Ops
`No agent found in pool Hosted VS2017 which satisfies the specified demands:
     powershell
     Agent.Version -gtVersion 1.95.0 `

Organisation Azure Dev Ops
`No agent found in pool Hosted VS2017 which satisfies the specified demands:
     powershell
     vstest
     Agent.Version -gtVersion 2.115.0 
`

When I disable the MSCRM Tool Installer, then the agent starts up OK but obviously the other MSCRM tools won't run.

Have you experienced this issue before?

**Comment by reimondot** [comment]
Our release pipelines have also suddenly broke this week with the same error:

No agent found in pool Hosted VS2017 which satisfies the specified demands:
 powershell
 Agent.Version -gtVersion 1.95.0

To be sure, I've also just tested it out in a separate dev ops instance by creating a release definition with just 1 task and can confirm the MSCRM Tool Installer extension returns the same error: No agent found in pool Hosted VS2017 which satisfies the specified demands:
 powershell
 Agent.Version -gtVersion 1.95.0

Since the D365 build tools hasn't changed in the past few days I'm guessing a recent update to Azure Dev Ops has broken it?

**Comment by reimondot** [comment]
@crmdruid While waiting for this issue to be resolved, I've found a temporary workaround which is to use the v9 of the import/publish tasks instead of the newer v10/v11 ones as the older v9 doesn't require the MSCRM Tools task.

**Comment by crmdruid** [comment]
@reimondot thanks for the feedback, currently I'm using the package deployer, a few people have recommended using an older version of the task, how do I do this?

Whether I use the import task or any of the others, I am only able to select the latest version.

![image](https://user-images.githubusercontent.com/7306269/55030501-6951b600-5071-11e9-9114-4339f2c6af3a.png)

![image](https://user-images.githubusercontent.com/7306269/55030570-8be3cf00-5071-11e9-83a8-8b7963577a97.png)

**Comment by reimondot** [comment]
@crmdruid On mine I just click on the Task version dropdown and I get the other versions:

![image](https://user-images.githubusercontent.com/48751176/55044190-4ecd0c00-5074-11e9-92e5-92bd21aa31cb.png)

I've just tested it out on a different Azure Dev Ops instance and I think I know why yours is different. On my Azure Dev Ops instance, I had installed the D365 Build Tools quite a while ago back when version 9 was the latest version.

When I go to a brand new Azure Dev Ops instance and install the D365 Build Tools from scratch, I only get v11 which is the same as you. So unfortunately I don't think you will be able to use the same temporary workaround because you hadn't installed the previous versions.

Unfortunately I think in your case you'll need @WaelHamze to advise.

**Comment by WaelHamze** [comment]
@crmdruid @reimondot I have just tested this on Hosted Agent 2017 and it seems to be still working fine for me.

It looks like the agent is not picking up the fact that you have powershell installed on the build server.

You could try to manually add the capability and see if it helps to work around the issue: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#capabilities

You can also raise an Azure DevOps issue if this is happening on the hosted agents

**Comment by plumski** [comment]
This is what I am getting:

##[Error 1]
No agent found in pool Hosted which satisfies the specified demands:
     powershell
     Agent.Version -gtVersion 1.95.0 

Does anyway have solution?

**Comment by plumski** [comment]
I just added:

USER CAPABILITIES
powershell          6.1.3
and it works

**Comment by WaelHamze** [comment]
@plumski glad it works, I guess there is nothing wrong in the task as it requires powershell so better add this dependency.

**Comment by gabrieljunckes** [comment]
I had the issue and it was resolved when I added the _USER CAPABILITIES_ in the Agent Pool

![image](https://user-images.githubusercontent.com/4098571/55699321-6e721600-5a1e-11e9-93a4-5c89b9cf49c0.png)
