### ISSUE TITLE
Error when running MSCRM Package Deployer for Azure Devops

### ISSUE THREAD

**Issue by AdrianSayasane** [WaelHamze/dyn365-ce-vsts-tasks#94]
I'm currently getting the following error when running the task to run the 'MSCRM Package Deployer' task from Azure Devops.

> ##[error]The term 'New-Guid' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I'm using Version 10.0.22 of the task and have tested the package deployment works when running the package deployer outside of Devops. I've also confirmed I'm running the 'Set MSCRM Tool Installer' before.

**Comment by WaelHamze** [comment]
@AdrianSayasane seems like an issue with PowerShell on the environment you are using

**Comment by JadynWong** [comment]
Hi @WaelHamze,
Is it possible to use `[guid]::NewGuid()` instead of `New-Guid` to increase compatibility?
Currently, I manually modify the task file that has been executed.

https://github.com/WaelHamze/dyn365-ce-vsts-tasks/blob/19a2b913d56e80c8a53b6999b82dbbe2cf372b2d/BuildTools/Xrm.CI.Framework.BuildTools/Tasks/MSCRMToolInstaller/MSCRMToolInstaller.ps1#L106
